# Generated by Django 4.0.5 on 2022-06-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhq_state', models.BooleanField()),
                ('xhs_state', models.BooleanField()),
                ('wg_state', models.BooleanField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.floor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.location_type'),
        ),
    ]
