# Generated by Django 4.0.5 on 2022-06-29 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100, verbose_name='设备编码')),
                ('type', models.CharField(max_length=100, verbose_name='设备类型')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(max_length=100, verbose_name='具体位置')),
                ('state', models.CharField(max_length=10, verbose_name='设备状态')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='楼层')),
            ],
        ),
        migrations.CreateModel(
            name='Location_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt_name', models.CharField(max_length=100, verbose_name='位置类型')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhq_state', models.BooleanField(default=True, verbose_name='灭火器状态')),
                ('xhs_state', models.BooleanField(default=True, verbose_name='消火栓状态')),
                ('wg_state', models.BooleanField(default=True, verbose_name='外观及标识状态')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.equipment', verbose_name='设备ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='巡检人员')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.floor', verbose_name='所在楼层'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xunjiansys.location_type', verbose_name='位置类型'),
        ),
    ]
